spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: demo-spring-boot-application
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer:
    producer:
      bootstrap-servers: localhost:9092
